eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Confetti
    username: root
    password: Yxg3955376
    driver-class-name: com.mysql.jdbc.Driver